server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

logging:
  level:
    org.springframework: INFO
    com.sentinel: DEBUG

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true