version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: sentinel-postgres
    environment:
      POSTGRES_DB: sentinel
      POSTGRES_USER: sentinel_user
      POSTGRES_PASSWORD: sentinel_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./initdb:/docker-entrypoint-initdb.d

  redis:
    image: redis:7
    container_name: sentinel-redis
    ports:
      - "6379:6379"

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sentinel-api
    depends_on:
      - postgres
      - redis
    ports:
      - "8080:8080"
    env_file:
      - .env

volumes:
  postgres_data:
